server:
  port: 8200
  servlet:
    context-path: /back
frontend-url: http://localhost:8100/front
app:
  # 必須是 gateway 的 domain
  login-url: http://localhost:8300${server.servlet.context-path}/login/cas
sso:
  server-url: https://cas.example.org:8443/cas
  logout-url: ${sso.server-url}/logout